name: PR Open Notification

on:
  pull_request:
    types: [opened]

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Comment PR opened on Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const regex = /(\w+-\d+)/;
            const match = pr.title.match(regex);
            
            if (match) {
              const issuePrefix = match[1];
              const issueNumber = issuePrefix.split('-')[1];
              
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: `PR [#${pr.number}](${pr.html_url}) opened from branch \`${pr.head.ref}\`.`
              });
            } else {
              console.log("Issue number not found in PR title.");
            }
