name: Link PRs to Issues

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  link-to-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Link PR to issue
      uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_token }}
          script: |
            const issuePrefix = "${{ vars.PROJECT_PREFIX }}";
            const prTitle = context.payload.pull_request.title;
            const issueNumberMatch = prTitle.match(new RegExp(`${issuePrefix}-(\\d+)`));
            if (issueNumberMatch) {
              const issueNumber = issueNumberMatch[1];
              const prNumber = context.payload.pull_request.number;

              const commentBody = `Linked Pull Reqiest: #${prNumber}`;

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: commentBody
              });
            }
