name: "AUTOMATION: PR Merged Notification"

on:
  pull_request:
    types: [closed]

env:
  IGNORE_PREFIX: ${{ vars.IGNORE_PREFIX }}

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Comment PR merged on Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;

            const ignore_prefix = process.env.IGNORE_PREFIX;

            // Check if the source branch has 'no-issue' prefix
            if (pr.head.ref.startsWith(ignore_prefix)) {
              console.log(`Skipping PR from branch '${pr.head.ref}' (${ignore_prefix} prefix)`);
              return;
            }

            const regex = /(\w+-\d+)/;
            const match = pr.title.match(regex);
            
            if (match) {
              const issuePrefix = match[1];
              const issueNumber = issuePrefix.split('-')[1];

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: `PR [#${pr.number}](${pr.html_url}) merged! Branch \`${pr.head.ref}\` has been deleted.`
              });
            } else {
              console.log("Issue number not found in PR title.");
              process.exit(1);
            }
